# Numpy

* Linear Algebra Library
* numerical computing
* to handle large multi-dimensional arrays and matrices
* mathematical function to operate efficiently

Advantages:
1. **Efficient Arrays** of homogenous data types
2. **Mathematical Functions**  operating elementwise on arrays
3. **Linear Algebra Operations**
4. **Random Number Generation**
5. **Integration with other Libraries**
6. **Memory Efficiency**

In [2]:
import numpy as np

## Numpy Arrays

- vectors (1-dimensional)
- matrices (generally 2-dimensional, but can have one row or one column)

In [3]:
# turn a list into an array
ghg = [4,8,2,1,90]
type(np.array(ghg))

numpy.ndarray

In [4]:
# turn a list into a matrix
zou = [[89,98,2,], [894, 30, 43], [894, 34,98]]
np.array(zou)

array([[ 89,  98,   2],
       [894,  30,  43],
       [894,  34,  98]])

### Built-in methods/functions

| function/method  | use |        
|----------|-----------|
| `np.arange(start, end+1, space)` | return evenly spaced values within a given interval <br> default space: 1 |
| `np.zeros()`| to create zero arrays or matrices |
| `np.ones()` | to create one arrays or matrices 
| `np.linspace(start, stop, num)` | return evenly spaced values within a given interval, <br> but **indicating the amount of values supposed to be generated (num)** <br> *includes end value* |
| `np.eye()` | creates an identity matrix (#columns = #rows)|
| `np.random.rand()` | creates an array of the given shape/length and fills it with random samples of a *uniform distribution* `[0,1)` <br> **only one bracket `()` needed for matrix creation!**|
| `np.random.randn()` |return sample(s) from the *standard normal distribution* <br> **only one bracket `()` needed for matrix creation!**|
| `np.random.randint(start, end+1, (num))` | return random integers for given interval, indicating the amount of values supposed to be generated (num) <br> shape of output determined with `num`, `(x,y)` creates matrix, just `x` creates array, no `num` input creates a single number |


*Creating matrices with numpy functions requires two round brackets!*  
e.g. `np.zeros((x,y))`; creates a matrix with x rows and y columns

In [7]:
# arange
print(np.arange(5, 56))
print(np.arange(5,56, 5))

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54 55]
[ 5 10 15 20 25 30 35 40 45 50 55]


In [8]:
# zero array
print(np.zeros(9))

# zero matrix
print(np.zeros((8,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# one array
print(np.ones(7))

# one matrix
print(np.ones((4,6)))

[1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [16]:
# same interval, different amount of values to be generated
print(np.linspace(9,39, 90))
print(np.linspace(9,39, 9))

[ 9.          9.33707865  9.6741573  10.01123596 10.34831461 10.68539326
 11.02247191 11.35955056 11.69662921 12.03370787 12.37078652 12.70786517
 13.04494382 13.38202247 13.71910112 14.05617978 14.39325843 14.73033708
 15.06741573 15.40449438 15.74157303 16.07865169 16.41573034 16.75280899
 17.08988764 17.42696629 17.76404494 18.1011236  18.43820225 18.7752809
 19.11235955 19.4494382  19.78651685 20.12359551 20.46067416 20.79775281
 21.13483146 21.47191011 21.80898876 22.14606742 22.48314607 22.82022472
 23.15730337 23.49438202 23.83146067 24.16853933 24.50561798 24.84269663
 25.17977528 25.51685393 25.85393258 26.19101124 26.52808989 26.86516854
 27.20224719 27.53932584 27.87640449 28.21348315 28.5505618  28.88764045
 29.2247191  29.56179775 29.8988764  30.23595506 30.57303371 30.91011236
 31.24719101 31.58426966 31.92134831 32.25842697 32.59550562 32.93258427
 33.26966292 33.60674157 33.94382022 34.28089888 34.61797753 34.95505618
 35.29213483 35.62921348 35.96629213 36.30337079 36.

In [17]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
# uniform distribution
# random.rand array
print(np.random.rand(8))

# random.rand matrix; caution: one bracket, two values!
print(np.random.rand(8,2))

[0.65177472 0.57384436 0.62315518 0.69701813 0.33314493 0.63743041
 0.35476725 0.71702625]
[[0.38209836 0.9620591 ]
 [0.70235626 0.06382102]
 [0.56278618 0.9251303 ]
 [0.50070505 0.03238894]
 [0.28634271 0.83176836]
 [0.45920274 0.30648286]
 [0.07046856 0.694151  ]
 [0.70691071 0.13790036]]


In [24]:
# standard normal distribution

# axis zero from left to right
print(np.random.randn(3))  

# axis zero downward
print(np.random.randn(9,1))

[0.9497436  1.16417594 0.20613087]
[[ 0.82895394]
 [ 0.40889015]
 [ 1.83744319]
 [-0.72949282]
 [-0.88755003]
 [ 1.15918054]
 [-0.65925897]
 [-0.28590442]
 [-1.43580048]]


In [28]:
# random integers

# single number
print(np.random.randint(1,901))

# array
print(np.random.randint(2, 247, 6))

# matrix
print(np.random.randint(6, 46, (5,3)))


728
[ 33  64 142  62  69 150]
[[42 10 43]
 [45 10 36]
 [42 10  9]
 [22 34 24]
 [19 28 38]]


### Attributes and Methods

NumPy arrays are implemented as `ndarray` class

```python
class numpy.ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)
```

that pocesses a number of attributes and methods.

`ndarray` is a placeholder for any variable containing an ndarray.

| method  | use |        
|----------|-----------|
| `ndarray.reshape()` | returns an array with the same data in a new shape |
| `ndarray.max()`| leave brackets empty, gives maximum value |
| `ndarray.argmax()`| leave brackets empty, gives *index* of maximum value |
| `ndarray.min()`| leave brackets empty, gives minimum value |
| `ndarray.argmin()`| leave brackets empty, gives *index* of minimum value |

| attribute  | use |        
|----------|-----------|
|`ndarray.shape` | returns shape of the array |
| `nd.array.dtype`| returns data type of the object in the array |


In [37]:
# create arrays to work with
obj = np.arange(30)
ranobj = np.random.randint(90,300, 22)

print(type(obj))
print(type(ranobj))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [46]:
# number of values has to fit the shape
newshape_obj = obj.reshape(5,6)
print(newshape_obj)
print(type(newshape_obj))

# shape attribute (NO BRACKETS!)
print(newshape_obj.shape)

# reshape again and call shape immediately
print(newshape_obj.reshape(15,2).shape)

# data type attribute
print(ranobj.dtype)

# other methods
print(ranobj.min())
print(ranobj.argmin())

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
<class 'numpy.ndarray'>
(5, 6)
(15, 2)
int64
94
11


## Indexing and Selection

### 1-D array
* same as python lists

### 2-D array
* general format is `arr_2d[row][col]` or `arr_2d[row,col]` 
* Caution: **slicing with comma separation**

* slicing a matrix *"from top right corner"*

### Fancy Indexing
* selecting rows or columns out of order with double square brackets `[[]]`
* possible to select every i-th element of an array using `::`
* example:
    * `print(mat2[3::8, ::6])` 
    * `3::8` -> specifies the row indices. It means start selecting rows from index 3 (inclusive) and select every 8th row thereafter
    * `::6` -> specifies the column indices. It means select every 6th column starting from the beginning.

### Boolean Indexing
*  possible to perform selection of `ndarray` elements using boolean indexing
*  possible to compare elements of an array to a scalar
*  create a boolean array and use it for filtering out elements of an original array that reside on same "places" as False elements of the boolean array
*  *For which values in the array it the statement true?*


In [69]:
# create arrays to work with
obj = np.arange(30)
ranobj = np.random.randint(90,300, 22)

mat = np.random.randint(340, 500, (3,3))

In [70]:
# array
# grab values with indexing
print(obj[29])
print(obj[6:])
print(ranobj[7:9])

29
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[276 289]


In [85]:
# matrix
print(mat)

# grab a whole row:
print(mat[2])

# grab specific value from row:
print(mat[2][1])
print(mat[2,1])

# slicing: all rows, last column
print(mat[:,2])

# slicing: last two rows, last two columns
print(mat[1:,1:])

# slicing: first two rows, last two columns
print(mat[:2,1:])

[[354 359 455]
 [467 445 419]
 [439 414 483]]
[439 414 483]
414
414
[455 419 483]
[[445 419]
 [414 483]]
[[359 455]
 [445 419]]


In [93]:
mat2 = np.random.randint(300,984, (10,9))
print(mat2)

# fancy indexing:
# selecting rows with index 3,6,2 and 8
print(mat2[[3, 6, 2, 8], :])

# selecting columns with index 3,6,2 and 8
print(mat2[:,[3, 6, 2, 8]])

# select every i-th element
print(mat2[3::8, ::6])

[[972 879 583 477 534 424 904 945 455]
 [670 421 572 897 949 717 898 572 897]
 [975 934 685 431 367 467 495 554 582]
 [725 799 837 507 490 715 346 824 552]
 [635 659 323 474 773 690 905 727 605]
 [593 585 405 789 463 834 778 431 852]
 [941 466 855 486 741 781 378 794 719]
 [940 332 957 776 445 375 555 877 687]
 [620 444 695 509 927 576 321 716 606]
 [526 835 338 671 939 701 655 421 417]]
[[725 799 837 507 490 715 346 824 552]
 [941 466 855 486 741 781 378 794 719]
 [975 934 685 431 367 467 495 554 582]
 [620 444 695 509 927 576 321 716 606]]
[[477 904 583 455]
 [897 898 572 897]
 [431 495 685 582]
 [507 346 837 552]
 [474 905 323 605]
 [789 778 405 852]
 [486 378 855 719]
 [776 555 957 687]
 [509 321 695 606]
 [671 655 338 417]]
[[725 346]]


In [99]:
print(obj)

# boolean indexing
print(obj > 12)

# create boolean area to filter elements for which statement is FALSE
boo_obj = obj < 8
print(boo_obj)

# filter elements based on boolean array
print(obj[boo_obj])

# works as well in one go
print(obj[obj > 20])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[False False False False False False False False False False False False
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True False False False False
 False False False False False False False False False False False False
 False False False False False False]
[0 1 2 3 4 5 6 7]
[21 22 23 24 25 26 27 28 29]


## Arithmetic Operations

In [104]:
# adds values pairwise (doesn't just paste the arrays together)
print(obj + obj)

# multiplies pairwise
print(obj*obj)

print(obj - obj)

print(obj / obj)

print(1/obj)

print(obj**8)


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58]
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361 400 441 484 529 576 625 676 729 784 841]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909
 0.08333333 0.07692308 0.07142857 0.06666667 0.0625     0.05882353
 0.05555556 0.05263158 0.05       0.04761905 0.04545455 0.04347826
 0.04166667 0.04       0.03846154 0.03703704 0.03571429 0.03448276]
[           0            1          256         6561        65536
       390625      1679616      5764801     16777216     43046721
    100000000    214358881    429981696    815730721   1475789056
   2562890625   4294967296   6975757441  11019960576  16983563041
  2560

/var/folders/dp/xjkh2hmd75l5n7n96tm19qqm0000gn/T/ipykernel_1317/1748352072.py:8: RuntimeWarning: invalid value encountered in divide
  print(obj / obj)
/var/folders/dp/xjkh2hmd75l5n7n96tm19qqm0000gn/T/ipykernel_1317/1748352072.py:9: RuntimeWarning: divide by zero encountered in divide
  print(1/obj)


### Universal Array Functions

In [105]:
print(np.sqrt(obj))

print(np.exp(obj))

print(np.max(obj))

print(np.sin(obj))

print(np.log(obj))


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739 3.87298335 4.         4.12310563
 4.24264069 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152
 4.89897949 5.         5.09901951 5.19615242 5.29150262 5.38516481]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06 3.26901737e+06
 8.88611052e+06 2.41549528e+07 6.56599691e+07 1.78482301e+08
 4.85165195e+08 1.31881573e+09 3.58491285e+09 9.74480345e+09
 2.64891221e+10 7.20048993e+10 1.95729609e+11 5.32048241e+11
 1.44625706e+12 3.93133430e+12]
29
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021
 -0.53657292  0.42016704  0.99060736  0.65028784 -0.2879

/var/folders/dp/xjkh2hmd75l5n7n96tm19qqm0000gn/T/ipykernel_1317/2243797892.py:9: RuntimeWarning: divide by zero encountered in log
  print(np.log(obj))
